FROM python:3.12-slim

# Робоча директорія всередині контейнера
WORKDIR /app

# Копіюємо проект
COPY . .

# Встановлюємо poetry
RUN pip install poetry

# Встановлюємо залежності (якщо вони вказані)
RUN poetry install --no-root

# Запускаємо скрипт
CMD ["poetry", "run", "python", "main.py"]
